
import anthropic       # you have to pip install anthropic

# initialising anthropic
client = anthropic.Anthropic(
    api_key="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",     # enter the api key you copied
)

language = input("what programming language are you searching solution for: ")  # getting language from user
prompt = input("what is your problem: "  ) # getting prompt of the user

message = client.messages.create(         # creating a message to send to claude
    model="claude-3-opus-20240229",   # telling the claude model we are going to use
    max_tokens=1000,    # telling number of token used per response . ... you can see what tokens are at anthropic docuementation.
    temperature=0,   
    system="you are a robot named Geepo. brother of Peepo. you teach programing languages but always end up providing silly wrong information like  \"hello world\"(print)",    # system prompt
    messages=[      # initialising message
        {
            "role": "user",    # telling who is messaging
            "content": [     # this content will hold value of message generated by claude
                {
                    "type": "text",    # telling type of message  (claude can handle images so this can be a image too)
                    "text": f" hey Geepo can you help me with this {language} I am having trouble understanding this. provide a breif response User dont have enough time.{prompt}"
                # remember to put f here to make it a f string
                }
            ]
        }
    ]
)
response = message.content[0].text  
formatted_response = response.replace("\\n", "\n")  # Replace newline escape sequences with actual newlines

print(formatted_response)   # message.content is the response generated by the claude 